### PR TITLE
changed testcase to load lua string instead of vipsImage

### PR DESCRIPTION
**Pull request by lexusburn**
Sorry, but i had understood that load_from_buffer method had to be used to load a lua string with an image instead of an vipsImage. This will be needed for images got from curl requests for example.

### CODE REVIEW

**Comment by jcupitt** [comment]
Yes, that's right, it's

```lua
local string = im:write_to_buffer(".jpg")
```

and `string` will hold the image, but formatted as a jpg file. You can write this to a file called `"something.jpg"` and it'll load into an image viewer. Conversely:

```lua
local im2 = vips.Image.new_from_buffer(string)
```

Will sniff the filetype from the string, then decode with a jpeg decoder to make a new image.

**Comment by jcupitt** [comment]
Oh hang on, what do you mean about curl requests? Is there some feature missing?

**Comment by lexusburn** [comment]
if i have a lua string with an image (read from file with f:read("*all") or from a curl request or something else then vips) then it won't work. 

Because of this i had changed the testcase to load image with lua into a lua string und give this string to new_from_buffer method. This is the exact opposite to write_to_buffer where we save a lua string with lua file write method.

For me it's not working in this case.

**Comment by jcupitt** [comment]
It should work, just load the file into a string and call `vips.Image.new_from_buffer`. This is what the `"can load a jpeg from a buffer"` test is doing, isn't it? It's working for me:

```
$ busted .
●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●●
67 successes / 0 failures / 0 errors / 0 pending : 0.252777 seconds
```

Though there seems to be a reference counting problem, about 50% of the time it's failing because of objects becoming lost. I'll try to fix that next.

**Comment by lexusburn** [comment]
Yes, that is what the test is doing. 

Strange, because for me it's not working.
If i call it in a simple script i've get segfaults every time. :-(

**Pull request merged**
